import type { BrandDef } from './brands';

type Cat = BrandDef['category'];

// Brands that appear in the catalogue but had no brand page. Descriptions are deliberately factual: they state the product
// type and where to buy, not manufacturer claims. `aliases` are the leading words of product names that belong to the brand.
const mk = (slug: string, name: string, category: Cat, what: string, aliases?: string[]): BrandDef => ({
  slug,
  name,
  category,
  tagline: `${name} ${what} in Australia`,
  description: `Browse the ${name} ${what} we list, with Australia-wide freight and a 10% cryptocurrency discount. Ask us for the manufacturer specification sheet and Australian road-legal status before ordering.`,
  ...(aliases ? { aliases } : {}),
});

export const EXTRA_BRANDS: BrandDef[] = [
  // E-bikes
  mk('pedego', 'Pedego', 'Electric Bikes', 'electric bikes and batteries'),
  mk('ampler', 'Ampler', 'Electric Bikes', 'electric bikes'),
  mk('smartmotion', 'SmartMotion', 'Electric Bikes', 'electric bikes'),
  mk('gepida', 'Gepida', 'Electric Bikes', 'electric bikes'),
  mk('rad-power', 'Rad Power Bikes', 'Electric Bikes', 'electric bikes and batteries', ['Rad Power', 'Rad']),
  mk('larry-vs-harry', 'Larry vs Harry', 'Electric Bikes', 'cargo bikes', ['Larry vs Harry', 'Larry']),
  mk('triobike', 'Triobike', 'Electric Bikes', 'cargo bikes'),
  mk('miride', 'MiRiDER', 'Electric Bikes', 'folding electric bikes'),
  mk('leitner', 'Leitner', 'Electric Bikes', 'folding electric bikes'),
  mk('qualisports', 'Qualisports', 'Electric Bikes', 'folding electric bikes'),
  mk('dahon', 'Dahon', 'Electric Bikes', 'folding electric bikes'),
  mk('engwe', 'Engwe', 'Electric Bikes', 'electric bikes and batteries'),
  mk('michael-blast', 'Michael Blast', 'Electric Bikes', 'cruiser e-bikes', ['Michael Blast', 'Michael']),
  mk('murf', 'Murf', 'Electric Bikes', 'cargo cruiser e-bikes'),
  mk('electra', 'Electra', 'Electric Bikes', 'electric bikes'),
  mk('ampere', 'Ampere', 'Electric Bikes', 'moped-style e-bikes'),
  mk('fatboy', 'Fatboy', 'Electric Bikes', 'fat tyre e-bikes'),
  mk('fatfish', 'Fatfish', 'Electric Bikes', 'fat tyre e-bikes'),
  mk('vamos', 'Vamos', 'Electric Bikes', 'folding e-bikes'),
  mk('mamba', 'Mamba', 'Electric Bikes', 'folding e-bikes'),
  mk('easybike', 'Easybike', 'Electric Bikes', 'folding e-bikes'),
  // Scooters
  mk('xiaomi', 'Xiaomi', 'Electric Scooters', 'electric scooters and parts'),
  mk('navee', 'Navee', 'Electric Scooters', 'electric scooters'),
  mk('anyhill', 'AnyHill', 'Electric Scooters', 'electric scooters'),
  mk('ausom', 'Ausom', 'Electric Scooters', 'electric scooters'),
  mk('mukuta', 'Mukuta', 'Electric Scooters', 'electric scooters'),
  mk('niu', 'NIU', 'Electric Scooters', 'electric scooters', ['Niu']),
  mk('e-twow', 'E-TWOW', 'Electric Scooters', 'electric scooters'),
  mk('mercane', 'Mercane', 'Electric Scooters', 'electric scooters'),
  mk('fluid', 'Fluid', 'Electric Scooters', 'electric scooters'),
  mk('pure-electric', 'Pure Electric', 'Electric Scooters', 'electric scooters', ['Pure']),
  mk('emove', 'EMove', 'Electric Scooters', 'electric scooters'),
  mk('zero', 'Zero', 'Electric Scooters', 'electric scooters'),
  mk('teverun', 'Teverun', 'Electric Scooters', 'electric scooters'),
  mk('solar', 'Solar', 'Electric Scooters', 'electric scooters'),
  // Skateboards and self-balancing
  mk('propulsion-board', 'Propulsion Board', 'Electric Skateboards', 'electric skateboards', ['Propulsion Board', 'Propulsion']),
  mk('aboard', 'Aboard', 'Electric Skateboards', 'electric skateboards'),
  mk('lacroix', 'Lacroix', 'Electric Skateboards', 'electric skateboards'),
  mk('veteran', 'Veteran', 'Electric Unicycles', 'electric unicycles'),
  mk('swagtron', 'Swagtron', 'Electric Unicycles', 'hoverboards and personal EVs'),
  mk('hover-1', 'Hover-1', 'Electric Unicycles', 'hoverboards'),
  mk('leaperkim', 'Leaperkim', 'Electric Unicycles', 'electric unicycles'),
  mk('gyroor', 'Gyroor', 'Electric Unicycles', 'hoverboards'),
  mk('bullet', 'Bullet', 'Electric Unicycles', 'hoverboards and go-kart attachments'),
  mk('vivid', 'Vivid', 'Electric Unicycles', 'hoverboards'),
  mk('e-glide', 'E-Glide', 'Electric Unicycles', 'hoverboards'),
  // Kids and off-road
  mk('ampd-bros', 'Ampd Bros', 'Kids & E-Dirt Bikes', 'electric bikes and kids bikes', ['Ampd Bros', 'Ampd']),
  mk('arctic-leopard', 'Arctic Leopard', 'Kids & E-Dirt Bikes', 'electric dirt bikes'),
  mk('rerode', 'Rerode', 'Kids & E-Dirt Bikes', 'electric dirt bikes'),
  mk('gotrax', 'Gotrax', 'Kids & E-Dirt Bikes', 'go-karts and scooters'),
  mk('e-ride', 'E Ride', 'Kids & E-Dirt Bikes', 'electric dirt bikes', ['E Ride']),
  mk('ktm', 'KTM', 'Kids & E-Dirt Bikes', 'electric balance bikes'),
  mk('husqvarna', 'Husqvarna', 'Kids & E-Dirt Bikes', 'electric balance bikes'),
  mk('gasgas', 'GASGAS', 'Kids & E-Dirt Bikes', 'electric balance bikes'),
  mk('mondraker', 'Mondraker', 'Kids & E-Dirt Bikes', 'kids e-bikes'),
  mk('bulls', 'Bulls', 'Kids & E-Dirt Bikes', 'kids e-bikes'),
  mk('mototec', 'MotoTec', 'Kids & E-Dirt Bikes', 'pit bikes'),
  mk('torrot', 'Torrot', 'Kids & E-Dirt Bikes', 'electric pit bikes'),
  mk('kayo', 'Kayo', 'Kids & E-Dirt Bikes', 'electric motocross bikes'),
  mk('burmax', 'Burmax', 'Kids & E-Dirt Bikes', 'go-karts'),
  mk('triad', 'Triad', 'Kids & E-Dirt Bikes', 'drift trikes'),
  // Mobility
  mk('solax', 'Solax', 'Mobility Scooters', 'mobility scooters'),
  mk('tzora', 'Tzora', 'Mobility Scooters', 'mobility scooters'),
  mk('monarch', 'Monarch', 'Mobility Scooters', 'mobility scooters'),
  mk('equipmed', 'Equipmed', 'Mobility Scooters', 'mobility scooters'),
  // Parts, safety, carry
  mk('bosch', 'Bosch', 'Accessories & Components', 'e-bike batteries and chargers'),
  mk('shimano', 'Shimano', 'Accessories & Components', 'e-bike batteries, chargers and brake parts'),
  mk('schwalbe', 'Schwalbe', 'Accessories & Components', 'e-bike tyres'),
  mk('tektro', 'Tektro', 'Accessories & Components', 'brake rotors and pads'),
  mk('swissstop', 'SwissStop', 'Accessories & Components', 'brake pads'),
  mk('bafang', 'Bafang', 'Accessories & Components', 'mid-drive conversion kits'),
  mk('bell', 'Bell', 'Accessories & Components', 'helmets'),
  mk('kask', 'Kask', 'Accessories & Components', 'helmets'),
  mk('knog', 'Knog', 'Accessories & Components', 'bike lights'),
  mk('moon', 'Moon', 'Accessories & Components', 'bike lights'),
  mk('topeak', 'Topeak', 'Accessories & Components', 'racks and bags'),
  mk('fox-racing', 'Fox Racing', 'Accessories & Components', 'helmets', ['Fox Racing']),
  mk('troy-lee-designs', 'Troy Lee Designs', 'Accessories & Components', 'helmets', ['Troy Lee Designs']),
  mk('alpinestars', 'Alpinestars', 'Accessories & Components', 'riding jackets'),
  mk('rixen-kaul', 'Rixen & Kaul', 'Accessories & Components', 'baskets and racks', ['Rixen & Kaul']),
  mk('thousand', 'Thousand', 'Accessories & Components', 'helmets'),
  mk('lumos', 'Lumos', 'Accessories & Components', 'smart helmets'),
  mk('proviz', 'Proviz', 'Accessories & Components', 'high-vis jackets'),
  mk('blackburn', 'Blackburn', 'Accessories & Components', 'racks'),
  mk('entity', 'Entity', 'Accessories & Components', 'inner tubes'),
  mk('freedom-to-ride', 'Freedom to Ride', 'Accessories & Components', 'inner tubes', ['Freedom to Ride']),
];
