import fs from 'fs';
import path from 'path';

// Let's create helper to generate product items
function createProduct(
  name: string,
  price: number,
  category: string,
  subcategory: string,
  subSubcategory: string,
  badge: 'Best Seller' | 'Popular' | 'Best Value' | 'Premium' | 'Sale' | 'New' | 'none',
  motorType: 'Rear Hub' | 'Front Hub' | 'Mid-Drive' | 'Dual Motor' | 'Hub Drive',
  sensorType: 'Torque Sensor' | 'Cadence Sensor' | 'Gyroscopic' | 'Throttle',
  compliance: 'EN15194 Certified' | 'Off-Road Private Land' | 'CE Certified',
  brakeType: 'Hydraulic Disc' | 'Mechanical Disc' | 'Regenerative' | 'V-Brake',
  batteryRange: 'Under 50km' | '50km+ Long Range',
  motor: string,
  battery: string,
  range: string,
  topSpeed: string,
  brakes: string,
  weight: string,
  payload: string,
  frame: string,
  gears: string
) {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return {
    slug,
    name,
    price,
    category,
    subcategory,
    subSubcategory,
    badge,
    featured: false,
    filters: {
      motorType,
      sensorType,
      compliance,
      brakeType,
      batteryRange,
    },
    description: `${name} is engineered for Australian conditions with superior quality components, high torque motors, and reliable lithium battery tech.`,
    shortDescription: `${name} featuring high torque motor, heavy-duty frame, and long-range battery.`,
    images: [`https://picsum.photos/seed/${slug}/1200/900`],
    specs: {
      motor,
      battery,
      range,
      topSpeed,
      brakes,
      weight,
      payload,
      frame,
      gears,
    },
  };
}

// 1. EBIKES (+70 new items -> 220 total)
export const NEW_EBIKES = [
  // Urban Commuters
  createProduct('Orbea Vibe Mid H30', 4399, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Best Seller', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Mahle X35+ 250W Rear Hub', 'Mahle 248Wh Integrated', 'Up to 70 km', '25 km/h (AU Compliant)', 'Magura MT2 Hydraulic Disc', '15.5 kg', '120 kg', 'Orbea Vibe Hydro Alloy', 'Shimano Deore 10-Speed'),
  createProduct('Kalkhoff Endeavour 1.B Move', 3699, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 65Nm', 'Bosch PowerPack 500Wh', 'Up to 95 km', '25 km/h (AU Compliant)', 'Tektro T275 Hydraulic Disc', '23.8 kg', '130 kg', 'Kalkhoff Integrale 0.5 Alloy', 'Shimano Acera 8-Speed'),
  createProduct('Gazelle Medeo T9 HMB', 3899, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Best Value', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Active Line Plus 50Nm', 'Bosch PowerPack 400Wh', 'Up to 85 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic Disc', '22.4 kg', '130 kg', 'Gazelle Low-Step Hydroformed', 'Shimano Acera 9-Speed'),
  createProduct('Merida eSpresso City 200 EQ', 3299, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'none', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano STEPS E5000 40Nm', 'Shimano E8014 418Wh', 'Up to 80 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '23.1 kg', '120 kg', 'eSpresso City Lite Alloy', 'Shimano Altus 8-Speed'),
  createProduct('Focus Planet² 5.6 Wave', 4199, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 65Nm', 'Bosch PowerTube 500Wh', 'Up to 100 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '24.2 kg', '130 kg', '7005 Hydroformed Alloy Wave', 'Shimano Altus 8-Speed'),
  createProduct('Velectrix Urban Street Pulse', 2499, 'electric-bikes', 'urban-commuter-ebikes', 'lightweight-urban-ebikes', 'New', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bafang 250W Rear Hub', '36V 11.6Ah LG Cells', 'Up to 60 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '19.8 kg', '110 kg', '6061 Lightweight Alloy', 'Microshift 8-Speed'),
  createProduct('Cube Touring Hybrid ONE 400', 2699, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Best Value', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Active Line 40Nm', 'Bosch PowerTube 400Wh', 'Up to 75 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '23.5 kg', '125 kg', 'Superlite Aluminium Trekking', 'Shimano Tourney 9-Speed'),
  createProduct('Specialized Turbo Como SL 4.0', 4999, 'electric-bikes', 'urban-commuter-ebikes', 'lightweight-urban-ebikes', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Specialized SL 1.1 240W', 'Specialized 320Wh Battery', 'Up to 100 km', '25 km/h (AU Compliant)', 'TRP Flow Set Hydraulic Disc', '21.5 kg', '125 kg', 'E5 Aluminium Step-Through', 'Shimano Nexus 5-Speed Internal'),
  createProduct('Trek Allant+ 8 ST', 5999, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX 85Nm', 'Bosch PowerTube 625Wh', 'Up to 120 km', '25 km/h (AU Compliant)', 'Shimano MT520 4-Piston', '24.8 kg', '136 kg', 'High-performance Hydroformed Alloy', 'Shimano Deore 10-Speed'),
  createProduct('NCM Milano Max N7', 2599, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bafang MAX Mid-Drive 80Nm', '36V 16Ah 576Wh Lithium', 'Up to 100 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '27.0 kg', '125 kg', 'Aluminium 6061 Step-Thru', 'Shimano Nexus 7-Speed Hub'),

  // Step-Through Commuters
  createProduct('DiroDi Rover Plus Low-Step 48V', 2899, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Best Seller', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 250W/750W Bafang Rear Hub', '48V 15Ah 720Wh LG Cells', 'Up to 85 km', '25 km/h (AU Compliant)', 'Logan Hydraulic Disc 180mm', '28.5 kg', '150 kg', 'High-tensile Low-Step Alloy', 'Shimano Altus 7-Speed'),
  createProduct('Eunorau E-Fat-Step Pro', 2899, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 500W Bafang Fat Hub', '48V 15Ah LG Battery', 'Up to 75 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '29.0 kg', '140 kg', 'Step-Through Fat Alloy', 'Shimano Tourney 7-Speed'),
  createProduct('Mokwheel Basalt Deluxe ST', 2999, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'New', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 250W High-Torque Hub', '48V 19.6Ah 940Wh Samsung', 'Up to 110 km', '25 km/h (AU Compliant)', 'Tektro HD-M275 Hydraulic', '32.0 kg', '160 kg', 'Power Station Inverter Frame', 'Shimano 7-Speed Megarange'),
  createProduct('Reid Urban eBike Step-Through Pro', 1799, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Ananda Rear Hub', '36V 10.4Ah Panasonic Cells', 'Up to 60 km', '25 km/h (AU Compliant)', 'Tektro Mechanical Disc', '21.0 kg', '110 kg', 'Reid Hydroformed 6061 Alloy', 'Shimano Tourney 7-Speed'),
  createProduct('Pedal Comet 3 Pro Disc', 1699, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Sale', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bafang 250W Rear Hub', '36V 10.4Ah Integrated', 'Up to 55 km', '25 km/h (AU Compliant)', 'Hydraulic Disc Brakes', '20.5 kg', '110 kg', 'Lightweight Step-Through Alloy', 'Shimano Tourney 7-Speed'),
  createProduct('SmartMotion Catalyst V2 ST', 3199, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Premium', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '36V 250W High Torque Rear Hub', '36V 15.6Ah 560Wh LG', 'Up to 90 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '24.5 kg', '120 kg', 'Endurance Step-Through Alloy', 'Shimano Alivio 9-Speed'),
  createProduct('Gepida Alboin 2000 CRS', 4299, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 65Nm', 'Bosch PowerTube 500Wh', 'Up to 100 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '24.9 kg', '130 kg', 'Hydroformed 6061 Alloy Wave', 'Shimano Deore 10-Speed'),
  createProduct('Aventon Soltera.2 Special Edition', 1999, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'New', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '36V 350W Brushless Rear Hub', '36V 9.6Ah LG Removable', 'Up to 70 km', '25 km/h (AU Compliant)', 'Tektro Mechanical Disc', '18.5 kg', '115 kg', 'Single-Butted 6061 Alloy', 'Shimano 7-Speed'),
  createProduct('NCM T3S Plus Commuter', 1999, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', 'Das-Kit X15 Rear Hub 250W', '36V 12Ah 432Wh Das-Kit', 'Up to 70 km', '25 km/h (AU Compliant)', 'Tektro Disc Brakes', '23.0 kg', '120 kg', 'Aluminium 6061 Low Step', 'Shimano Altus 7-Speed'),
  createProduct('Fiido C11 Pro Long Range', 1299, 'electric-bikes', 'urban-commuter-ebikes', 'step-through-commuters', 'Best Value', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '500W High Efficiency Hub', '500Wh Removable Battery', 'Up to 90 km', '25 km/h (AU Compliant)', 'Hydraulic Disc Brakes', '24.5 kg', '120 kg', 'Urban Commuter Step-Thru', 'Shimano 7-Speed'),

  // Step-Over Commuters
  createProduct('Cannondale Moterra Neo 3', 6499, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line CX 85Nm', 'Bosch PowerTube 750Wh', 'Up to 130 km', '25 km/h (AU Compliant)', 'Shimano MT420 4-Piston Hydraulic', '25.5 kg', '140 kg', 'SmartForm C2 Alloy Frame', 'Shimano Deore 12-Speed'),
  createProduct('Trek Dual Sport+ 2 Stagger', 3299, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Best Seller', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Hyena Rear Hub 250W 40Nm', '250Wh Internal Battery', 'Up to 55 km', '25 km/h (AU Compliant)', 'Tektro HD-M275 Hydraulic', '17.4 kg', '136 kg', 'Alpha Gold Aluminium', 'Shimano Altus 9-Speed'),
  createProduct('Specialized Turbo Vado 3.0', 4699, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Specialized 1.3 50Nm Mid-Drive', 'Specialized U2-530 530Wh', 'Up to 110 km', '25 km/h (AU Compliant)', 'Shimano BR-MT200 Hydraulic', '24.1 kg', '136 kg', 'E5 Aluminium Fitness Frame', 'Shimano Alivio 9-Speed'),
  createProduct('Giant Explore E+ 3 Power', 3499, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Best Value', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'SyncDrive Core Yamaha 50Nm', 'EnergyPak 500Wh Side-Release', 'Up to 120 km', '25 km/h (AU Compliant)', 'Tektro HD-M275 Hydraulic', '23.8 kg', '130 kg', 'ALUXX SL-Grade Aluminium', 'Shimano Alivio 9-Speed'),
  createProduct('Merida eSpresso 300 SE', 3799, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'none', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano STEPS E5000 40Nm', 'Shimano E8010 504Wh', 'Up to 100 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '22.9 kg', '120 kg', 'eSpresso Lite Hydroformed Alloy', 'Shimano Alivio 9-Speed'),
  createProduct('Polygon Path E+ 5', 3899, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano STEPS E6100 60Nm', 'Shimano BT-E8035 504Wh', 'Up to 105 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '21.5 kg', '120 kg', 'ALX City Hydroformed Alloy', 'Shimano Deore 10-Speed'),
  createProduct('Norco Indie VLT 2', 3199, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Sale', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano STEPS E5000 40Nm', 'Shimano E8035 504Wh Integrated', 'Up to 95 km', '25 km/h (AU Compliant)', 'Tektro HD-M275 Hydraulic', '22.0 kg', '125 kg', 'Indie VLT Hydroformed Alloy', 'Shimano Alivio 9-Speed'),
  createProduct('Cube Kathmandu Hybrid Pro 600', 4799, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX 85Nm', 'Bosch PowerTube 625Wh', 'Up to 130 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '26.2 kg', '135 kg', 'Aluminium Superlite Gravity Casting', 'Shimano Deore 10-Speed'),
  createProduct('Orbea Vector H20', 3799, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Popular', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Mahle X35 250W Rear Hub', 'Mahle 248Wh Internal', 'Up to 70 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '16.2 kg', '115 kg', 'Orbea Vector Alloy Frame', 'Shimano Sora 9-Speed'),
  createProduct('Focus Planet² 5.7 Diamond', 4599, 'electric-bikes', 'urban-commuter-ebikes', 'step-over-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line CX 85Nm', 'Bosch PowerTube 500Wh', 'Up to 110 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '23.9 kg', '130 kg', '7005 Hydroformed Alloy Diamond', 'Shimano Deore 10-Speed'),

  // Belt Drive & Lightweight
  createProduct('Tenways CGO600 Pro Belt', 2899, 'electric-bikes', 'urban-commuter-ebikes', 'belt-drive-commuters', 'Best Seller', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '250W Brushless Rear Hub 35Nm', '36V 10Ah 360Wh Portable OLED', 'Up to 100 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '16.0 kg', '120 kg', '6061 Aircraft Grade Alloy', 'Gates Carbon Drive CDN Belt'),
  createProduct('Kalkhoff Endeavour 5.B Excite', 6999, 'electric-bikes', 'urban-commuter-ebikes', 'belt-drive-commuters', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line CX 85Nm', 'Bosch PowerTube 625Wh', 'Up to 125 km', '25 km/h (AU Compliant)', 'Shimano MT420 Hydraulic 4-Piston', '26.8 kg', '130 kg', 'Integrale 0.6 Hydroformed Alloy', 'Gates Belt Drive + Nexus 5 Internal'),
  createProduct('Specialized Turbo Vado SL 4.0 Step-Through', 4999, 'electric-bikes', 'urban-commuter-ebikes', 'lightweight-urban-ebikes', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Specialized SL 1.1 Custom Lightweight', '320Wh Fully Integrated Lithium', 'Up to 130 km (with RE)', '25 km/h (AU Compliant)', 'Tektro HD-R290 Hydraulic', '15.0 kg', '125 kg', 'E5 Aluminium Step-Thru', 'Shimano Deore 10-Speed'),
  createProduct('Priority Current Hub Shift', 4999, 'electric-bikes', 'urban-commuter-ebikes', 'belt-drive-commuters', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '500W 140Nm Torque Mid-Drive', '500Wh Removable Battery', 'Up to 80 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Dual Piston', '24.0 kg', '135 kg', 'Ultralight 6061 Aluminium', 'Gates Carbon Drive CDX + Enviolo Automatiq'),
  createProduct('Ampler Stout Classic Belt', 4399, 'electric-bikes', 'urban-commuter-ebikes', 'belt-drive-commuters', 'New', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Ampler 250W Rear Hub Torque', '336Wh Integrated LG Cells', 'Up to 70 km', '25 km/h (AU Compliant)', 'Shimano M6100 Hydraulic Disc', '17.2 kg', '120 kg', '6061 Aluminium Classic Geometry', 'Gates Carbon Drive Cententrack'),

  // Cargo & Family
  createProduct('Riese & Müller Multicharger3 Mixte', 7999, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX Smart System 85Nm', 'Bosch PowerTube 750Wh', 'Up to 120 km', '25 km/h (AU Compliant)', 'Magura MT4/MT5 Hydraulic', '29.5 kg', '175 kg', 'Multicharger Mixte Low-Step Alloy', 'Shimano Deore 10-Speed LinkGlide'),
  createProduct('Cannondale Cargowagen Neo 2', 5699, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Cargo Line 85Nm', 'Bosch PowerPack 545Wh (Dual Battery Ready)', 'Up to 90 km', '25 km/h (AU Compliant)', 'Shimano MT420 4-Piston Hydraulic', '33.0 kg', '200 kg', 'SmartForm C2 Alloy Heavy Duty Cargo', 'Shimano Deore 10-Speed'),
  createProduct('E-Mono Atlas Urban Cargo', 2799, 'electric-bikes', 'cargo-family-ebikes', 'compact-cargo', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 250W Bafang Heavy Hub', '48V 15Ah 720Wh Samsung', 'Up to 85 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc Brakes', '29.8 kg', '160 kg', 'Heavy Duty Long rear-rack Alloy', 'Shimano Altus 7-Speed'),
  createProduct('Eunorau G30 Max Cargo', 2999, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 500W High Torque Hub', '48V 15Ah + Optional 2nd Battery', 'Up to 110 km', '25 km/h (AU Compliant)', 'Hydraulic Disc 180mm', '31.0 kg', '180 kg', 'Reinforced Utility Cargo Frame', 'Shimano Altus 8-Speed'),
  createProduct('Lectric XPedition Dual Battery', 2899, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '750W Rear Hub 85Nm Torque', 'Dual 48V 14Ah (1344Wh Total)', 'Up to 120 km', '25 km/h (AU Compliant)', 'Hydraulic Disc 180mm Rotors', '34.0 kg', '205 kg', 'Long-Tail Utility Alloy 6061', 'Shimano 7-Speed Heavy Duty'),

  // Cargo Long Tail, Compact & Front Loader
  createProduct('Tern GSD S00 LX Cargo Plus', 9499, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Cargo Line 85Nm 400% Assist', 'Dual Bosch PowerPack 1000Wh Total', 'Up to 160 km', '25 km/h (AU Compliant)', 'Magura MT5 4-Piston Hydraulic', '34.8 kg', '200 kg', 'Ultra-Heavy-Duty 6061-T6 Folding Handlebar', 'Enviolo Heavy Duty Stepless Internal'),
  createProduct('Benno Boost E 10D Performance', 6599, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX 85Nm', 'Bosch PowerPack 500Wh', 'Up to 90 km', '25 km/h (AU Compliant)', 'Magura MT30 Hydraulic Disc', '28.0 kg', '200 kg', '6061 Aluminium Etutility Frame', 'Shimano Deore 10-Speed'),
  createProduct('Yuba Spicy Curry V3', 5899, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Cargo Line 85Nm', 'Bosch PowerPack 500Wh', 'Up to 80 km', '25 km/h (AU Compliant)', 'Magura MT32 Hydraulic', '31.0 kg', '200 kg', '6061 T6 Low-Center-of-Gravity Alloy', 'Shimano Deore 10-Speed'),
  createProduct('Rad Power RadWagon 4 Pro', 3199, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Geared Rear Hub', '48V 14Ah 672Wh Samsung', 'Up to 75 km', '25 km/h (AU Compliant)', 'Tektro Aries Mechanical Disc', '34.8 kg', '158 kg', 'Extended Longtail Alloy Frame', 'Shimano Altus 7-Speed'),
  createProduct('Pedego Stretch Cargo', 4299, 'electric-bikes', 'cargo-family-ebikes', 'long-tail-cargo', 'none', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '48V 250W/500W Rear Hub Drive', '48V 13Ah 624Wh Lithium', 'Up to 70 km', '25 km/h (AU Compliant)', 'SRAM BB7 Mechanical Disc', '33.0 kg', '180 kg', 'Low-Step Heavy Cargo Alloy', 'Shimano Acera 7-Speed'),

  // Compact Cargo
  createProduct('Tern HSD P9 Performance', 5899, 'electric-bikes', 'cargo-family-ebikes', 'compact-cargo', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 65Nm', 'Bosch PowerPack 500Wh', 'Up to 110 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '25.7 kg', '170 kg', 'Tern HSD 6061-T6 FlatFold', 'Shimano Alivio 9-Speed'),
  createProduct('Blix Packa Genie Dual Battery', 3699, 'electric-bikes', 'cargo-family-ebikes', 'compact-cargo', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '750W High-Torque Rear Hub', 'Dual 48V 12.8Ah (1228Wh Total)', 'Up to 130 km', '25 km/h (AU Compliant)', 'Hydraulic Disc 180mm', '32.0 kg', '181 kg', 'Compact Step-Thru Cargo Alloy', 'Shimano Acera 8-Speed'),
  createProduct('Benno RemiDemi 9D', 4499, 'electric-bikes', 'cargo-family-ebikes', 'compact-cargo', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 65Nm', 'Bosch PowerPack 400Wh', 'Up to 80 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '22.0 kg', '180 kg', 'Etutility Compact Fat Frame', 'Shimano Acera 9-Speed'),
  createProduct('Yuba Kombi E5', 3999, 'electric-bikes', 'cargo-family-ebikes', 'compact-cargo', 'Best Value', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano STEPS E5000 40Nm', 'Shimano 418Wh Battery', 'Up to 70 km', '25 km/h (AU Compliant)', 'Shimano Hydraulic Disc', '29.0 kg', '200 kg', 'Compact Chromoly Steel Utility', 'Shimano Altus 9-Speed'),
  createProduct('Specialized Haul ST', 4299, 'electric-bikes', 'cargo-family-ebikes', 'compact-cargo', 'Premium', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '700W Custom Rear Hub Drive', '772Wh Removable Battery', 'Up to 100 km', '25 km/h (AU Compliant)', 'Tektro HD-T535 4-Piston Hydraulic', '35.0 kg', '190 kg', 'One-Size-Fits-All Extra Tough Alloy', 'Microshift 9-Speed Heavy Duty'),

  // Front Loader Box Bikes
  createProduct('Riese & Müller Packster 70 Vario', 11999, 'electric-bikes', 'cargo-family-ebikes', 'front-loader-cargo', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Cargo Line Smart System 85Nm', 'Dual Bosch PowerTube 1250Wh', 'Up to 140 km', '25 km/h (AU Compliant)', 'Tektro Auriga Comp 4-Piston', '42.0 kg', '200 kg', 'Packster EPP Box Front Loader Alloy', 'Enviolo 380 Continuous Hub + Belt'),
  createProduct('Urban Arrow Family Cargo Active', 9499, 'electric-bikes', 'cargo-family-ebikes', 'front-loader-cargo', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Cargo Line 85Nm', 'Bosch PowerPack 500Wh', 'Up to 80 km', '25 km/h (AU Compliant)', 'Tektro Dorado Hydraulic Disc', '50.0 kg', '250 kg', 'Aluminium Front Loader with EPP Box', 'Enviolo Heavy Duty Stepless'),
  createProduct('Cube Cargo Sport Dual Hybrid', 8299, 'electric-bikes', 'cargo-family-ebikes', 'front-loader-cargo', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Cargo Line 85Nm', 'Dual Bosch PowerPack 1000Wh', 'Up to 120 km', '25 km/h (AU Compliant)', 'Magura C2 Hydraulic Disc', '48.5 kg', '220 kg', 'High Performance Aluminium Cargo Box', 'Shimano Deore 10-Speed'),
  createProduct('Larry vs Harry Bullitt E-Steps', 8999, 'electric-bikes', 'cargo-family-ebikes', 'front-loader-cargo', 'none', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano STEPS EP8 85Nm', 'Shimano BT-E8016 630Wh', 'Up to 100 km', '25 km/h (AU Compliant)', 'TRP Slate T4 4-Piston Hydraulic', '27.5 kg', '180 kg', '7005 T6 Heat Treated Aluminium', 'Shimano XT 11-Speed'),
  createProduct('Triobike Cargo E-Drive', 9899, 'electric-bikes', 'cargo-family-ebikes', 'front-loader-cargo', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Brose Drive S 90Nm', '508Wh Integrated Lithium', 'Up to 70 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc Brakes', '31.0 kg', '230 kg', 'Lightweight Danish Front Cargo Alloy', 'Shimano Zee 10-Speed'),

  // eMTB Full Suspension & Hardtail
  createProduct('Merida eOne-Forty 400', 5499, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano EP6 85Nm Mid-Drive', 'Shimano E8036 630Wh Integrated', 'Up to 100 km', '25 km/h (AU Compliant)', 'Shimano MT420 4-Piston Hydraulic', '24.2 kg', '140 kg', 'eONE-FORTY LITE Hydroformed Alloy', 'Shimano Deore 11-Speed'),
  createProduct('Specialized Turbo Levo Alloy', 7999, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Specialized 2.2 Custom Rx Trail 90Nm', 'Specialized M3-500 500Wh', 'Up to 90 km', '25 km/h (AU Compliant)', 'SRAM Guide RE 4-Piston Hydraulic', '23.8 kg', '136 kg', 'M5 Premium Alloy 150mm Travel', 'SRAM SX Eagle 12-Speed'),
  createProduct('Trek Rail 5 Gen 3', 7299, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX 85Nm', 'Bosch PowerTube 625Wh', 'Up to 110 km', '25 km/h (AU Compliant)', 'Tektro HD-M745 4-Piston Hydraulic', '24.8 kg', '136 kg', 'Alpha Platinum Aluminium 150mm', 'Shimano Deore 12-Speed'),
  createProduct('Giant Trance X Advanced E+ 2', 8499, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'SyncDrive Pro Yamaha 85Nm', 'EnergyPak Smart 625Wh', 'Up to 120 km', '25 km/h (AU Compliant)', 'Shimano Deore XT 4-Piston', '22.9 kg', '136 kg', 'Advanced-Grade Carbon Composite 140mm', 'Shimano Deore 12-Speed'),
  createProduct('Norco Sight VLT A2', 7899, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano EP8 85Nm', 'Removable 720Wh Battery', 'Up to 115 km', '25 km/h (AU Compliant)', 'Shimano MT520 4-Piston', '25.1 kg', '135 kg', 'All-Mountain Alloy 150mm Travel', 'Shimano Deore 12-Speed'),

  createProduct('Specialized Turbo Levo Expert', 13999, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Specialized 2.2 Custom Rx 90Nm', 'Specialized M3-700 700Wh', 'Up to 130 km', '25 km/h (AU Compliant)', 'SRAM Code RS 4-Piston Hydraulic', '22.1 kg', '136 kg', 'FACT 11m Full Carbon 150mm Travel', 'SRAM GX Eagle AXS Wireless 12-Spd'),
  createProduct('Trek Rail 9.8 GX AXS', 12499, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX Smart System 85Nm', 'Bosch PowerTube 750Wh', 'Up to 130 km', '25 km/h (AU Compliant)', 'SRAM Code R 4-Piston Hydraulic', '23.4 kg', '136 kg', 'OCLV Mountain Carbon 150mm Travel', 'SRAM GX Eagle AXS 12-Speed'),
  createProduct('Giant Reign E+ 1 Pro', 9999, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'SyncDrive Pro Yamaha 85Nm', 'EnergyPak Smart 750Wh', 'Up to 125 km', '25 km/h (AU Compliant)', 'Shimano Deore XT 4-Piston', '24.1 kg', '136 kg', 'ALUXX SL-Grade Alloy 160mm Maestro', 'Shimano Deore XT 12-Speed'),
  createProduct('Merida eOne-Sixty 7000', 9299, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'none', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano EP801 85Nm', 'TrendPower 750Wh Battery', 'Up to 120 km', '25 km/h (AU Compliant)', 'Shimano XT 4-Piston Hydraulic', '22.8 kg', '140 kg', 'eONE-SIXTY CFA II Carbon/Alloy 160mm', 'Shimano XT 12-Speed'),
  createProduct('Cannondale Moterra Neo Carbon 2', 10499, 'electric-bikes', 'electric-mountain-bikes', 'full-suspension-emtb', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance CX 85Nm', 'Bosch PowerTube 750Wh', 'Up to 135 km', '25 km/h (AU Compliant)', 'Shimano XT 4-Piston Hydraulic', '23.5 kg', '140 kg', 'BallisTec Carbon Front Triangle 150mm', 'Shimano XT 12-Speed'),

  createProduct('Specialized Turbo Tero 3.0', 4899, 'electric-bikes', 'electric-mountain-bikes', 'hardtail-emtb', 'Best Seller', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Specialized 2.0E 50Nm Mid-Drive', 'Specialized U2-530 530Wh', 'Up to 110 km', '25 km/h (AU Compliant)', 'Shimano BR-MT200 Hydraulic', '21.8 kg', '136 kg', 'E5 Aluminium Trail Hardtail', 'Shimano Alivio 9-Speed'),
  createProduct('Trek Marlin+ 6 Hardtail', 3899, 'electric-bikes', 'electric-mountain-bikes', 'hardtail-emtb', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Active Line Plus 50Nm', 'Bosch CompactTube 400Wh', 'Up to 80 km', '25 km/h (AU Compliant)', 'Tektro HD-M275 Hydraulic', '21.2 kg', '136 kg', 'Alpha Gold Aluminium Hardtail', 'Shimano CUES 9-Speed'),
  createProduct('Giant Talon E+ 29er', 3299, 'electric-bikes', 'electric-mountain-bikes', 'hardtail-emtb', 'Best Value', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'SyncDrive Core Yamaha 50Nm', 'EnergyPak Side-Release 500Wh', 'Up to 100 km', '25 km/h (AU Compliant)', 'Tektro HD-M275 Hydraulic', '21.5 kg', '130 kg', 'ALUXX-Grade Aluminium 29er', 'Shimano Alivio 9-Speed'),
  createProduct('Merida eBig.Nine 400', 3999, 'electric-bikes', 'electric-mountain-bikes', 'hardtail-emtb', 'none', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Shimano EP6 85Nm', 'Shimano E8036 630Wh', 'Up to 115 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '22.0 kg', '135 kg', 'eBIG.NINE LITE Aluminium 29er', 'Shimano Deore 10-Speed'),
  createProduct('Cube Reaction Hybrid Performance', 3699, 'electric-bikes', 'electric-mountain-bikes', 'hardtail-emtb', 'New', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 75Nm', 'Bosch PowerTube 500Wh', 'Up to 100 km', '25 km/h (AU Compliant)', 'Shimano MT200 Hydraulic', '23.1 kg', '135 kg', 'Aluminium Superlite Gravity Casting 29er', 'Shimano 9-Speed'),

  // Foldable E-Bikes
  createProduct('Brompton Electric C Line 6-Speed', 5299, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Best Seller', 'Front Hub', 'Torque Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Brushless Front Hub Drive', '300Wh Detachable Bag Battery', 'Up to 70 km', '25 km/h (AU Compliant)', 'Dual Pivot Caliper Brakes', '17.4 kg', '110 kg', 'Hand-Brazed Steel Folding Frame', '6-Speed Wide-Range Hub/Derailleur'),
  createProduct('Tern Vektron Q9 Folding', 4899, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Active Line Plus 50Nm', 'Bosch PowerPack 400Wh', 'Up to 90 km', '25 km/h (AU Compliant)', 'Hydraulic Disc Brakes', '21.9 kg', '125 kg', 'Tern Vektron 7075-T6 Folding Frame', 'Shimano Alivio 9-Speed'),
  createProduct('Fiido D11 Compact Folder', 1499, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W High Torque Rear Hub', '36V 11.6Ah Seatpost Battery', 'Up to 60 km', '25 km/h (AU Compliant)', 'Mechanical Disc Brakes', '17.5 kg', '120 kg', 'Ultra-light Aviation Aluminium Alloy', 'Shimano 7-Speed'),
  createProduct('MiRiDER One GB3', 2899, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'New', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '250W Rear Hub Drive System', '36V 7Ah Samsung Lithium', 'Up to 45 km', '25 km/h (AU Compliant)', 'Hydraulic Disc Brakes', '17.2 kg', '120 kg', 'Die-Cast Magnesium Alloy Folding', 'Efneo 3-Speed Internal Gearbox'),
  createProduct('Leitner Folding E-Bike Step-Thru', 1599, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Sale', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Brushless Rear Hub Motor', '36V 10.4Ah Lithium Ion', 'Up to 50 km', '25 km/h (AU Compliant)', 'Tektro Mechanical Disc', '20.0 kg', '115 kg', 'Aluminium Alloy Low-Step Folding', 'Shimano 7-Speed'),

  createProduct('Tern Vektron S10 Gen 2', 5699, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Premium', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bosch Performance Line 65Nm', 'Bosch PowerPack 500Wh', 'Up to 110 km', '25 km/h (AU Compliant)', 'Magura MT4 Hydraulic Disc', '22.1 kg', '125 kg', 'Vektron Hydroformed Alloy OCL Joint', 'Shimano Deore 10-Speed'),
  createProduct('Qualisports Volador 20', 1899, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '350W Geared Brushless Hub', '36V 7Ah Samsung Seatpost', 'Up to 50 km', '25 km/h (AU Compliant)', 'Mechanical Disc Brakes', '17.0 kg', '110 kg', '6061 Aluminium Alloy Folding', 'Shimano 7-Speed'),
  createProduct('DAHON Unio E20', 2499, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Popular', 'Mid-Drive', 'Torque Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '36V 200W Mid-Drive Motor', '36V 9.5Ah Seatpost Battery', 'Up to 60 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '16.1 kg', '105 kg', 'Dalloy Sonus Aluminium Folding', '9-Speed Derailleur'),
  createProduct('Fiido D21 Lightweight Folder', 1699, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'none', 'Rear Hub', 'Torque Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Rear Hub Torque Motor', '36V 11.6Ah Seatpost Battery', 'Up to 80 km', '25 km/h (AU Compliant)', 'Mechanical Disc Brakes', '17.5 kg', '120 kg', 'Aviation Grade Magnesium Alloy', 'Shimano 7-Speed'),
  createProduct('Leitner Superlite Folding 20', 1699, 'electric-bikes', 'foldable-electric-bikes', 'compact-folding-bikes', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Geared Motor', '36V 10Ah Samsung Lithium', 'Up to 50 km', '25 km/h (AU Compliant)', 'Tektro Disc Brakes', '18.5 kg', '115 kg', 'Superlite Aluminium Alloy', 'Shimano 6-Speed'),

  createProduct('DiroDi Cortina Fat Tyre Folder', 2499, 'electric-bikes', 'foldable-electric-bikes', 'fat-tyre-folding-bikes', 'Best Seller', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 250W/750W Bafang Fat Motor', '48V 14Ah 672Wh LG Cells', 'Up to 75 km', '25 km/h (AU Compliant)', 'Hydraulic Disc 180mm', '28.0 kg', '135 kg', '6061 Fat Tyre Folding Alloy', 'Shimano Altus 7-Speed'),
  createProduct('Rad Power RadExpand 5', 2399, 'electric-bikes', 'foldable-electric-bikes', 'fat-tyre-folding-bikes', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Geared Hub Motor', '48V 14Ah 672Wh Samsung', 'Up to 70 km', '25 km/h (AU Compliant)', 'Tektro Aries Mechanical Disc', '28.3 kg', '125 kg', '6061 Heavy Duty Folding Frame', 'Microshift 7-Speed'),
  createProduct('Eunorau E-Fat-Step 20', 2299, 'electric-bikes', 'foldable-electric-bikes', 'fat-tyre-folding-bikes', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 500W Bafang Fat Motor', '48V 12.5Ah LG Cells', 'Up to 60 km', '25 km/h (AU Compliant)', 'Hydraulic Disc Brakes', '29.0 kg', '130 kg', 'Step-Thru Fat Folding Alloy', 'Shimano 7-Speed'),
  createProduct('Fiido M1 Pro Fat Folder', 1799, 'electric-bikes', 'foldable-electric-bikes', 'fat-tyre-folding-bikes', 'Sale', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '500W High Torque Hub', '48V 12.8Ah High Capacity', 'Up to 65 km', '25 km/h (AU Compliant)', 'Dual Disc Brakes', '25.0 kg', '120 kg', 'Full-Suspension Folding Alloy', 'Shimano 7-Speed'),
  createProduct('Engwe EP-2 Pro Fat Folder', 1699, 'electric-bikes', 'foldable-electric-bikes', 'fat-tyre-folding-bikes', 'New', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '750W Brushless Motor', '48V 13Ah Lithium Battery', 'Up to 60 km', '25 km/h (AU Compliant)', 'Tektro Mechanical Disc', '30.0 kg', '150 kg', '3-Step Folding Aluminium Alloy', 'Shimano 7-Speed'),

  // Fat Tyre & Lifestyle E-Bikes
  createProduct('Super73 S2 Hudson Blue', 4999, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Best Seller', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '250W/2000W Peak DC Rear Hub', '960Wh Removable Battery', 'Up to 120 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic 180mm 2-Piston', '33.0 kg', '150 kg', 'Aircraft-grade 6061-T6 Alloy', 'Single-Speed / Multi-Mode'),
  createProduct('DiroDi Rover Plus 750W', 3299, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Best Seller', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 750W Bafang High Torque', '48V 15Ah LG 720Wh', 'Up to 80 km', '25 km/h (AU Compliant)', 'Logan Hydraulic Disc 180mm', '31.5 kg', '150 kg', 'High-tensile Retro Moped Alloy', 'Shimano Altus 7-Speed'),
  createProduct('Michael Blast Greaser Classic', 3899, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bafang 250W/500W Geared Hub', '36V 13Ah Samsung Lithium', 'Up to 60 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc Brakes', '28.0 kg', '125 kg', 'A6061 Aluminium Vintage Boardtracker', 'Shimano Acera 7-Speed'),
  createProduct('Vallkree Scrambler 250W', 4199, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Premium', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '250W Dapu Rear Hub Engine', '48V 15Ah Samsung Lithium', 'Up to 70 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc Brakes', '33.0 kg', '140 kg', 'Custom Australian Designed Alloy Scrambler', 'Shimano Acera 7-Speed'),
  createProduct('Murf The Alpha Cargo Cruiser', 4499, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'New', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '500W Geared Rear Hub', '52V 20Ah 1040Wh Samsung', 'Up to 100 km', '25 km/h (AU Compliant)', 'Hydraulic Disc 4-Piston', '32.0 kg', '160 kg', 'Heavy Duty Beach Cargo Cruiser Alloy', 'Single-Speed / 7-Speed Option'),

  createProduct('Pedego Interceptor Cruiser', 3999, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'none', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '48V 250W/500W Rear Hub', '48V 15Ah Lithium Ion', 'Up to 80 km', '25 km/h (AU Compliant)', 'SRAM BB7 Mechanical Disc', '27.0 kg', '120 kg', '6061 Light-weight Aluminium Classic', 'Shimano Acera 7-Speed'),
  createProduct('Electra Townie Go! 7D', 2699, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'Best Value', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', 'Hyena Rear Hub Drive 250W', '250Wh Rear Rack Battery', 'Up to 50 km', '25 km/h (AU Compliant)', 'Mechanical Disc Brakes', '20.0 kg', '115 kg', '6061-T6 Flat Foot Technology Alloy', 'Shimano 7-Speed'),
  createProduct('Michael Blast Outsider', 3699, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bafang 250W/500W Rear Hub', '48V 14.5Ah LG Cells', 'Up to 70 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc', '30.0 kg', '130 kg', 'Cafe Racer Custom Alloy', 'Shimano Altus 7-Speed'),
  createProduct('Reid Classic E-Bike Cruiser', 1799, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'Sale', 'Front Hub', 'Cadence Sensor', 'EN15194 Certified', 'Mechanical Disc', '50km+ Long Range', '250W Ananda Front Hub', '36V 10.4Ah Panasonic Cells', 'Up to 55 km', '25 km/h (AU Compliant)', 'Tektro Mechanical Disc', '22.0 kg', '110 kg', 'Vintage Alloy Step-Thru Cruiser', 'Shimano Tourney 7-Speed'),
  createProduct('DiroDi Classico Cruiser', 2699, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'New', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '250W Bafang Rear Hub', '36V 14Ah LG Battery', 'Up to 80 km', '25 km/h (AU Compliant)', 'Logan Hydraulic Disc', '26.0 kg', '125 kg', 'Classic Dutch Vintage Cruiser Alloy', 'Shimano Altus 7-Speed'),

  createProduct('Super73 RX Mojave', 6499, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Premium', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '2000W Peak DC Rear Hub Drive', '960Wh Removable Battery', 'Up to 120 km', '25 km/h (AU Compliant)', 'Magura MT5e 4-Piston Hydraulic', '36.0 kg', '150 kg', 'Aircraft-Grade Alloy Full Suspension', 'Multi-Speed Electronic Select'),
  createProduct('DiroDi Rover Gen 6 1000W Dual', 3699, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Best Seller', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 1000W High Torque Bafang', '48V 20Ah 960Wh LG Cells', 'Up to 100 km', '25 km/h (AU Compliant)', 'Logan Hydraulic Disc 180mm', '33.0 kg', '160 kg', 'Retro Moped Heavy Duty Dual Seat', 'Shimano Altus 7-Speed'),
  createProduct('Michael Blast Vacay', 3799, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'classic-cruiser-ebikes', 'Popular', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', 'Bafang 250W/500W Geared Hub', '48V 14Ah Samsung Lithium', 'Up to 75 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic Disc Brakes', '29.0 kg', '130 kg', 'Beach Cruiser Low-Rider Alloy', 'Shimano Acera 7-Speed'),
  createProduct('Ampere X-Trail Moped', 3299, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'none', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '48V 750W Rear Hub Engine', '48V 16Ah LG Battery', 'Up to 80 km', '25 km/h (AU Compliant)', 'Hydraulic Disc 180mm', '32.0 kg', '145 kg', 'Rugged Steel Frame Moped Style', 'Shimano 7-Speed'),
  createProduct('Vallkree Black Cow 500W', 4699, 'electric-bikes', 'fat-tyre-lifestyle-ebikes', 'moped-style-ebikes', 'Premium', 'Rear Hub', 'Cadence Sensor', 'EN15194 Certified', 'Hydraulic Disc', '50km+ Long Range', '500W Dapu Rear Hub Drive', '48V 17.5Ah Samsung Lithium', 'Up to 85 km', '25 km/h (AU Compliant)', 'Tektro Hydraulic 4-Piston', '34.0 kg', '150 kg', 'Custom Australian Vintage Scrambler Alloy', 'Shimano Acera 7-Speed'),
];

console.log('NEW_EBIKES count:', NEW_EBIKES.length);
