// Generated by scripts/images.mjs - do not edit by hand. Re-run the script after adding photos.
export const PRODUCT_PLACEHOLDER = '/images/product-placeholder.svg';

export const PRODUCT_IMAGES: Record<string, string> = {

};
